  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Blogs"
  weight = 200
  identifier = "blogs"
  url = "/blogs/"

  [[main]]
  name = "Portfolio"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"

  [[main]]
  name = "Publications"
  weight = 400
  identifier = "publications"
  url = "/publications/"

  [[main]]
  name = "Talks"
  weight = 500
  identifier = "talks"
  url = "/talks/"

  [[main]]
  name = "Accomplishments"
  weight = 600
  identifier = "accomplishments"

  [[main]]
  name = "Awards"
  weight = 610
  identifier = "awards"
  url = "/awards/"
  parent = "accomplishments"  

  [[main]]
  name = "Certifications"
  weight = 620
  identifier = "certifications"
  url = "/certifications/"
  parent = "accomplishments"

  [[main]]
  name = "Contact"
  weight = 700
  identifier = "contact"
  url = "/contact/"

  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/imprint/"