
title = "I'm Osodo Rodney"
author = "Osodo Rodney"
copyright = "2020-{{ YEAR }}"
description = "Call me Osodo"
profilePicture = "images/profile.png"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["post"]
images = ["images/site-feature-image.png"]

doNotLoadAnimations = false
# Form Spree Contact Form
contactFormAction = "https://formspree.io/f/xrgjobww"
# Google Fonts
#googleFonts = ["Indie+Flower", "Roboto:ital,wght@0,100;0,400;0,700;1,400"]
# Google Site Verify
googleSiteVerify = "rodneyosodo.com"
singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
readMore = true
postSectionName = "blog"

# Side bar content ratio
[params]
  contentratio = 0.8
  images = ["images/site-feature-image.png"]

# hidesidebar = true
[outputs]
  home = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML"]
  term = ["HTML"]

reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'

# hidesidebar = true

[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

[plausibleAnalytics]
# domain = "example.com"
# serverURL = "https://analytics.example.com"

[umami]
# serverURL = "example.com"
# id = "94db1cb1-74f4-4a40-ad6c-962362670409"

## Math settings
[math]
enable = true  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "mathjax"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/rodneyosodo"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/rodneyosodo"

[[socialIcons]]
icon = "fab fa-gitlab"
title = "Gitlab"
url = "https://gitlab.com/0x6f736f646f"

[[socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/b1ackd0t"

[[socialIcons]]
icon = "fab fa-instagram"
title = "Instagram"
url = "https://www.instagram.com/rodneyosodo/"

[[socialIcons]]
icon = "fab fa-tiktok"
title = "TikTok"
url = "https://www.tiktok.com/@b1ackd0t"

[[socialIcons]]
icon = "fab fa-youtube"
title = "Youtube"
url = "https://www.youtube.com/@rodneyosodo"

[[socialIcons]]
icon = "fab fa-stack-overflow"
title = "StackOverflow"
url = "https://stackoverflow.com/users/9017060/black-dot"

[[socialIcons]]
icon = "fab fa-medium"
title = "Medium"
url = "https://rodneyosodo.medium.com/"

[[socialIcons]]
icon = "fab fa-spotify"
title = "Spotify"
url = "https://open.spotify.com/show/2MBoVx1mlX0kjHVrooqasf"

[social]
  twitter = "b1ackd0t"
